version: 0.2

env:
  variables:
    ENVIRONMENT: "prod"
    SPRING_PROFILES_ACTIVE: "prod"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - mvn install -DskipTests

  pre_build:
    commands:
      - echo Pre-build started on `date`
      - echo Compiling the application...
      - mvn compile

  build:
    commands:
      - echo Build started on `date`
      - echo Running tests...
      - mvn test
      - echo Packaging the application...
      - mvn package -DskipTests

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Preparing the artifact for deployment...
      - mv target/*.jar application.jar
      - echo $CODEBUILD_BUILD_ARN

artifacts:
  files:
    - application.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
